// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    baseUrl: '/js/',
    paths: {
      socket: '/socket.io/socket.io',
      bsend: '/libs/bsend',
      jquery: '/libs/jquery/jquery-1.9.1',
      jqueryUi: '/libs/jquery/jquery-ui-1.10.2.custom',
      jqueryMouse: '/libs/jquery/jquery.mousewheel',
      jqueryScrollbar: '/libs/jquery/jquery.jscrollpane',
      jqueryUiTime: '/libs/jquery/jquery-ui-timepicker-addon',
      jqueryGridster: '/libs/jquery/jquery.gridster',
      jqueryColorPicker: '/libs/jquery/farbtastic',
      jqueryUiAddTouch: '/libs/jquery/jquery.ui.touchpunch',
      jqueryDoubleTap: '/libs/jquery/jquery.doubletap',
      jqueryHotKeys: '/libs/jquery/jquery.hotkeys',
      jqueryJGrowl: '/libs/jquery/jquery.jgrowl',
      jqueryDownload: '/libs/jquery/jquery.download',
      jqueryTinyMCE: '/libs/tiny_mce/jquery.tinymce.min',
      jqueryCountdown: '/libs/jquery/jquery.countdown',
      jqueryPrettyPhoto: '/libs/jquery/jquery.prettyPhoto',
      jqueryMaxImage:'/libs/jquery/jquery.maximage',
      jqueryCustom:'/libs/jquery/custom',
      jqueryTabSlideOut:'/libs/jquery/jquery.tabSlideOut.v1.3',
      jqueryTinySort : '/libs/jquery/jquery.tinysort',
      fullCalendar : '/libs/jquery/fullcalendar',
      mouseIntent: '/libs/jquery/mwheelIntent',
      underscore: '/libs/backbone/underscore',
      backbone: '/libs/backbone/backbone',
      backboneIOSync: '/libs/backbone/backbone.iosync',
      backboneIOBind: '/libs/backbone/backbone.iobind',
      marionette: '/libs/backbone/backbone.marionette',
      bb: '/libs/bb.extend',
      text: '/libs/requirejs/text',
      async: '/libs/requirejs/async',
      goog: '/libs/requirejs/goog',
      propertyParser: '/libs/requirejs/propertyParser',
      depend: '/libs/requirejs/depend',
      font: '/libs/requirejs/font',
      noext: '/libs/requirejs/noext',
      modernizr: '/libs/modernizr',
      permission: '/js/permission',
      swfobject: '/libs/swfobject',
      modifyColor: '/libs/modifyColor',
      ga: '/libs/ga',
      waitUntil: '/libs/waitUntilExists',
      etc: '/js/etc',
      i: '/i',
      views: '/js/views'
    },
    shim: {
      backbone: {
        deps: ['underscore', 'jquery']
      },
      marionette: {
        deps: ['backbone']
      },
      fullCalendar: {
        deps: ['jquery']
      },
      jqueryMouse: {
        deps: ['jquery']
      },
      jqueryTinySort: {
        deps: ['jquery']
      },
      jqueryUi: {
        deps: ['jquery']
      },
      jqueryGridster: {
        deps: ['jquery', 'modernizr']
      },
      jqueryTinyMCE: {
        deps: ['jquery']
      },
      jqueryColorPicker: {
        deps: ['jquery']
      },
      jqueryHotKeys: {
        deps: ['jquery']
      },
      jqueryJGrowl: {
        deps: ['jquery']
      },
      jqueryCustom:{
         deps: ['jquery','jqueryMaxImage','jqueryTabSlideOut']
      },
      jqueryMaxImage: {
        deps: ['jquery']
      },
      jqueryTabSlideOut:{
         deps: ['jquery']
      },
      jqueryScrollbar: {
        deps: ['jquery', 'jqueryMouse', 'modernizr']
      },
      jqueryUiAddTouch: {
        deps: ['jqueryUi', 'jquery', 'modernizr']
      },
      jqueryDoubleTap: {
        deps: ['jquery', 'modernizr']
      },
      jqueryUiTime: {
        deps: ['jqueryUi', 'jquery']
      },
      mouseIntent: {
        deps: ['jquery']
      },
      backboneIOSync: {
        deps: ['backbone']
      },
      backboneIOBind: {
        deps: ['backbone']
      },
      jqueryDownload: {
        deps: ['jquery']
      }
    }
  });

require(['socket', 'jquery', 'underscore', 'backbone', 'views/appView', 'router', 'vm', 'ga', 'i/client/c', 'i/instance/c', 'i/profile/c', 'bsend', 'waitUntil', 'modernizr', 'jqueryUiAddTouch', 'jqueryDoubleTap','https://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js'], function(io, $, _, backbone, AppView, Router, Vm, _ga, Clients, Instances, Profiles, Bsend) {
    var ready;
    $(document).ready( function() {
       CFInstall.check({
         mode: "overlay",
       });
      var me, so, touch, ga;
      ga = _ga.Apply();
      so = io.connect();
      touch = Modernizr.touch ? true : false;
      me = {
        width: window.innerWidth,
        height: window.innerHeight,
        touch: touch,
        timezone:-(new Date()).getTimezoneOffset()/120
      };
      so.emit('connect', Bsend.je(me), function(err, data) {
          
        if (err) 
          return console.log('Unable to connect.');
        
        return ready(Bsend.jd(data), so,ga);
      });

    });
    return ready = function(data, so,ga) {
      var checkVisablity, clients, instances, profiles;
      checkVisablity = true;
      if (_.isString(document.webkitVisibilityState)) {
        if (document.webkitVisibilityState === 'prerender') {
          checkVisablity = false;
        } else if (document.webkitVisibilityState === 'preview') {
          checkVisablity = false;
        }
      }
      clients = new Clients(null, {
        s: so
      });
      instances = new Instances(null, {
        s: so
      });
      profiles = new Profiles(null, {
        s: so
      });
      //console.log(data);
      return instances.fetch({
                success: function() {
      return clients.fetch({
        success: function() {
          return profiles.fetch({
            success: function() {
                  window.___ = instances.first().id;
                  window.__l = data.loggedIn.loggedIn;
                  var p;
                  p = profiles.length > 0 ? profiles.first() : null;
                  return Router.initialize({
                    ___: {
                      view: Vm.create({}, 'AppView', AppView),
                      vm: Vm,
                      so: so,
                      u: data.loggedIn,
                      conf: data.conf,
                      c: clients.first(),
                      i: instances.first(),
                      p: p,
                      api: data.api,
                      ga: ga
                    }
                  })
               
            },error:function  (err, err2) {
             console.log('error profiles',err,err2)
            },data: {'_id': clients.first().get('profile')}});
        },error:function  (err, err2) {
          console.log('error clients',err,err2)
        },data: {'_id': instances.first().get('client')}});
       },error:function  (err, err2) {
          console.log('error instances',err,err2)
      },data: {'_id': data.i}});
    };
  });

}).call(this);
