// Generated by CoffeeScript 1.4.0
(function() {

  define(['require', 'jquery', 'underscore', 'bb', 'i/command/c', 'i/loader/c', 'i/role/c', 'text!/html/header.html','text!/html/footer.html'], function(require, $, _, Backbone, Commands, Loaders, Roles) {
    return Backbone.View.extend({
      id: 'top',
      tagName: 'header',
      initialize: function(options) {
        this.___ = options.___;
        this.on('ready', this.onLoginDone, this);
        this.render();
        return this.___.router.loadCss('/css/header.css', true);
      }
      ,events: {}
      ,render: function() {
        var that = this;
        var  logo;
        var Header = require('text!/html/header.html');
        var header = _.template(Header);
        this.$el.append(header({}));
        var Footer = require('text!/html/footer.html');
        var footer = _.template(Footer);
        $("body").append(footer({}));

      
        return this.onLoginDone();
      

      },
      onLoginDone: function() {
        return this.doneLoading();
      },
      doneLoading: function() {
        $('body > #content').show();
        return $('body > #loader').hide();
      }
    });
  });

}).call(this);
